CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(50) PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS dummy_stock_portfolio (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    stock_symbol VARCHAR(20) NOT NULL,
    quantity INT NOT NULL,
    purchase_price DECIMAL(10, 2) NOT NULL
);

INSERT INTO users (id, username, password) VALUES ('user001', 'investor_001', 'pass1234_company_user1') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user002', 'investor_002', 'pass1234_company_user2') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user003', 'investor_003', 'pass1234_company_user3') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user004', 'investor_004', 'pass1234_company_user4') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user005', 'investor_005', 'pass1234_company_user5') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user006', 'investor_006', 'pass1234_company_user6') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user007', 'investor_007', 'pass1234_company_user7') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user008', 'investor_008', 'pass1234_company_user8') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user009', 'investor_009', 'pass1234_company_user9') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user010', 'investor_010', 'pass1234_company_user10') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user011', 'investor_011', 'pass1234_company_user11') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user012', 'investor_012', 'pass1234_company_user12') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user013', 'investor_013', 'pass1234_company_user13') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user014', 'investor_014', 'pass1234_company_user14') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user015', 'investor_015', 'pass1234_company_user15') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user016', 'investor_016', 'pass1234_company_user16') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user017', 'investor_017', 'pass1234_company_user17') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user018', 'investor_018', 'pass1234_company_user18') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user019', 'investor_019', 'pass1234_company_user19') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user020', 'investor_020', 'pass1234_company_user20') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user021', 'investor_021', 'pass1234_company_user21') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user022', 'investor_022', 'pass1234_company_user22') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user023', 'investor_023', 'pass1234_company_user23') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user024', 'investor_024', 'pass1234_company_user24') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user025', 'investor_025', 'pass1234_company_user25') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user026', 'investor_026', 'pass1234_company_user26') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user027', 'investor_027', 'pass1234_company_user27') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user028', 'investor_028', 'pass1234_company_user28') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user029', 'investor_029', 'pass1234_company_user29') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user030', 'investor_030', 'pass1234_company_user30') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user031', 'investor_031', 'pass1234_company_user31') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user032', 'investor_032', 'pass1234_company_user32') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user033', 'investor_033', 'pass1234_company_user33') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user034', 'investor_034', 'pass1234_company_user34') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user035', 'investor_035', 'pass1234_company_user35') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user036', 'investor_036', 'pass1234_company_user36') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user037', 'investor_037', 'pass1234_company_user37') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user038', 'investor_038', 'pass1234_company_user38') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user039', 'investor_039', 'pass1234_company_user39') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user040', 'investor_040', 'pass1234_company_user40') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user041', 'investor_041', 'pass1234_company_user41') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user042', 'investor_042', 'pass1234_company_user42') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user043', 'investor_043', 'pass1234_company_user43') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user044', 'investor_044', 'pass1234_company_user44') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user045', 'investor_045', 'pass1234_company_user45') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user046', 'investor_046', 'pass1234_company_user46') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user047', 'investor_047', 'pass1234_company_user47') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user048', 'investor_048', 'pass1234_company_user48') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user049', 'investor_049', 'pass1234_company_user49') ON CONFLICT DO NOTHING;
INSERT INTO users (id, username, password) VALUES ('user050', 'investor_050', 'pass1234_company_user50') ON CONFLICT DO NOTHING;

INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user001', 'CVX', 53, 152.53);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user001', 'CSCO', 64, 56.87);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user001', 'NTPC.NS', 74, 196.39);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user002', 'WMT', 90, 145.19);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user002', 'AXISBANK.NS', 52, 952.49);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user002', 'PG', 100, 151.13);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user002', 'TATAMOTORS.NS', 30, 635.81);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user002', 'NTPC.NS', 36, 190.39);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user002', 'JPM', 53, 143.85);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user003', 'WIPRO.NS', 95, 422.16);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user003', 'SUNPHARMA.NS', 99, 1077.34);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user003', 'HINDUNILVR.NS', 86, 2567.92);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user003', 'JPM', 81, 146.72);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user004', 'ICICIBANK.NS', 62, 921.30);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user004', 'INTC', 73, 33.96);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user004', 'TCS.NS', 32, 3313.21);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user005', 'BAJAJFINSV.NS', 39, 1528.16);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user005', 'TSLA', 46, 225.03);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user005', 'NFLX', 51, 410.87);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user006', 'NTPC.NS', 16, 205.86);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user006', 'INTC', 72, 33.54);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user006', 'CVX', 25, 161.04);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user006', 'SBIN.NS', 34, 554.72);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user007', 'NFLX', 54, 389.48);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user007', 'TATAMOTORS.NS', 69, 600.61);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user007', 'BAC', 44, 30.58);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user007', 'LT.NS', 77, 2618.86);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user008', 'ICICIBANK.NS', 24, 990.20);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user008', 'CSCO', 82, 54.37);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user008', 'ULTRACEMCO.NS', 11, 7858.32);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user008', 'NTPC.NS', 12, 195.55);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user008', 'TSLA', 52, 214.58);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user008', 'JNJ', 37, 165.23);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user009', 'ASIANPAINT.NS', 89, 3283.25);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user009', 'WIPRO.NS', 58, 414.28);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user009', 'CSCO', 63, 53.64);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user009', 'RELIANCE.NS', 94, 2464.82);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user009', 'KOTAKBANK.NS', 40, 1755.28);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user010', 'META', 46, 290.50);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user010', 'INTC', 54, 33.54);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user010', 'ICICIBANK.NS', 32, 981.51);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user010', 'MRK', 63, 106.15);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user010', 'ITC.NS', 78, 442.18);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user011', 'AXISBANK.NS', 100, 1020.72);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user011', 'CVX', 83, 160.40);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user011', 'MA', 49, 385.02);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user011', 'AAPL', 11, 146.82);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user011', 'HD', 43, 298.78);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user011', 'HINDUNILVR.NS', 49, 2600.74);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user012', 'V', 65, 232.87);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user012', 'NFLX', 57, 390.90);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user012', 'BAC', 53, 30.98);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user012', 'INFY.NS', 58, 1405.67);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user012', 'PEP', 10, 167.33);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user013', 'VZ', 66, 35.44);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user013', 'CSCO', 16, 55.54);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user013', 'HINDUNILVR.NS', 43, 2420.89);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user013', 'INTC', 21, 35.39);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user013', 'HCLTECH.NS', 11, 1093.96);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user013', 'INFY.NS', 16, 1371.55);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user013', 'JPM', 75, 133.23);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user014', 'DIS', 21, 82.08);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user014', 'SUNPHARMA.NS', 49, 1074.26);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user014', 'INFY.NS', 94, 1410.54);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user015', 'BHARTIARTL.NS', 24, 852.41);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user015', 'WMT', 49, 144.62);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user015', 'VZ', 59, 33.29);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user015', 'ASIANPAINT.NS', 10, 3353.73);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user015', 'TSLA', 71, 211.44);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user015', 'GOOGL', 32, 2775.35);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user016', 'ITC.NS', 54, 470.76);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user016', 'NVDA', 56, 436.57);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user016', 'ASIANPAINT.NS', 70, 3251.24);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user016', 'INFY.NS', 75, 1335.07);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user016', 'AAPL', 47, 153.18);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user016', 'DIS', 82, 81.70);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user017', 'VZ', 19, 35.69);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user017', 'KOTAKBANK.NS', 22, 1857.76);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user017', 'PEP', 60, 163.17);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user017', 'BAJAJFINSV.NS', 63, 1563.88);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user017', 'JPM', 41, 137.03);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user017', 'NTPC.NS', 59, 198.35);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user018', 'V', 26, 220.24);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user018', 'ASIANPAINT.NS', 80, 3057.97);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user018', 'MSFT', 73, 313.04);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user019', 'DIS', 46, 82.79);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user019', 'NTPC.NS', 23, 207.98);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user019', 'UNH', 41, 465.27);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user019', 'MSFT', 79, 302.63);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user019', 'GOOGL', 48, 2778.70);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user019', 'MARUTI.NS', 15, 9180.20);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user020', 'CVX', 93, 155.60);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user020', 'PG', 25, 149.04);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user020', 'WMT', 74, 148.35);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user020', 'ASIANPAINT.NS', 37, 3292.62);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user020', 'ITC.NS', 57, 434.44);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user021', 'NVDA', 24, 440.57);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user021', 'RELIANCE.NS', 52, 2359.22);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user021', 'HINDUNILVR.NS', 46, 2516.59);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user022', 'MRK', 47, 106.19);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user022', 'NVDA', 99, 433.33);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user022', 'DIS', 35, 83.11);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user022', 'MA', 92, 388.39);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user022', 'CSCO', 19, 56.69);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user023', 'V', 28, 238.92);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user023', 'CVX', 21, 153.55);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user023', 'BAC', 86, 29.87);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user023', 'DIS', 32, 89.07);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user023', 'POWERGRID.NS', 93, 229.10);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user023', 'MARUTI.NS', 96, 9671.88);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user023', 'PEP', 32, 175.22);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user024', 'NFLX', 89, 417.15);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user024', 'BAJFINANCE.NS', 26, 6943.43);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user024', 'JNJ', 97, 153.27);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user024', 'DIS', 72, 88.51);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user025', 'INTC', 24, 36.24);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user025', 'PEP', 76, 177.47);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user025', 'META', 20, 288.19);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user025', 'KOTAKBANK.NS', 99, 1780.34);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user025', 'WMT', 49, 151.24);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user025', 'SBIN.NS', 69, 587.32);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user026', 'GOOGL', 61, 2882.72);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user026', 'POWERGRID.NS', 28, 241.20);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user026', 'HD', 34, 306.42);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user026', 'MA', 78, 375.96);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user026', 'CVX', 43, 167.31);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user027', 'NVDA', 50, 432.66);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user027', 'AXISBANK.NS', 62, 1016.99);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user027', 'BAJAJFINSV.NS', 33, 1523.19);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user027', 'VZ', 64, 35.77);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user028', 'AMZN', 83, 132.04);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user028', 'MA', 100, 390.02);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user028', 'ULTRACEMCO.NS', 19, 8419.77);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user028', 'UNH', 25, 458.24);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user029', 'LT.NS', 95, 2615.37);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user029', 'POWERGRID.NS', 60, 229.55);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user029', 'BHARTIARTL.NS', 76, 836.43);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user029', 'TSLA', 49, 210.26);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user029', 'ASIANPAINT.NS', 87, 3115.64);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user029', 'JPM', 97, 134.86);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user029', 'INTC', 60, 34.92);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user030', 'BAJFINANCE.NS', 89, 7270.23);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user030', 'VZ', 41, 34.58);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user030', 'BAJAJFINSV.NS', 97, 1569.41);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user030', 'NTPC.NS', 79, 195.20);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user031', 'BAJAJFINSV.NS', 96, 1476.64);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user031', 'PEP', 51, 171.64);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user031', 'NFLX', 41, 411.36);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user031', 'HCLTECH.NS', 86, 1192.64);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user031', 'AMZN', 23, 131.00);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user032', 'NTPC.NS', 35, 190.01);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user032', 'V', 77, 234.79);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user032', 'PG', 38, 147.27);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user032', 'HCLTECH.NS', 80, 1123.56);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user032', 'POWERGRID.NS', 14, 245.69);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user032', 'AXISBANK.NS', 96, 986.69);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user032', 'GOOGL', 31, 2709.21);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user033', 'TCS.NS', 100, 3176.01);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user033', 'INFY.NS', 18, 1400.09);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user033', 'MSFT', 35, 298.51);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user033', 'HCLTECH.NS', 52, 1177.27);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user034', 'ITC.NS', 36, 454.41);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user034', 'RELIANCE.NS', 89, 2297.79);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user034', 'GOOGL', 90, 2662.80);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user035', 'HDFCBANK.NS', 51, 1597.31);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user035', 'CVX', 75, 156.99);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user035', 'VZ', 13, 33.71);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user035', 'AMZN', 68, 131.41);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user036', 'CSCO', 49, 53.88);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user036', 'KO', 54, 59.77);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user036', 'HINDUNILVR.NS', 81, 2474.73);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user036', 'M&M.NS', 24, 1486.70);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user036', 'TSLA', 54, 216.54);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user037', 'WIPRO.NS', 64, 408.43);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user037', 'MRK', 46, 109.52);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user037', 'HD', 68, 298.25);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user037', 'MARUTI.NS', 93, 9512.06);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user037', 'VZ', 59, 36.24);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user037', 'RELIANCE.NS', 73, 2429.49);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user037', 'POWERGRID.NS', 19, 234.14);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user038', 'HD', 46, 291.10);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user038', 'ICICIBANK.NS', 57, 992.96);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user038', 'TATAMOTORS.NS', 87, 614.08);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user038', 'LT.NS', 36, 2685.05);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user038', 'ASIANPAINT.NS', 51, 3281.70);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user039', 'MRK', 32, 110.14);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user039', 'V', 47, 227.53);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user039', 'INFY.NS', 56, 1416.17);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user039', 'KOTAKBANK.NS', 68, 1877.80);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user039', 'NFLX', 51, 413.62);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user039', 'CVX', 43, 163.02);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user039', 'TCS.NS', 80, 3317.86);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user040', 'NFLX', 10, 413.70);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user040', 'GOOGL', 24, 2720.74);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user040', 'HCLTECH.NS', 55, 1167.90);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user040', 'KOTAKBANK.NS', 46, 1728.98);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user040', 'LT.NS', 62, 2575.29);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user040', 'VZ', 100, 35.48);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user041', 'HCLTECH.NS', 22, 1184.31);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user041', 'PEP', 80, 174.38);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user041', 'LT.NS', 36, 2664.96);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user042', 'AMZN', 34, 131.97);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user042', 'NVDA', 77, 452.87);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user042', 'HDFCBANK.NS', 78, 1558.99);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user042', 'PEP', 81, 166.89);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user042', 'POWERGRID.NS', 54, 242.63);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user042', 'M&M.NS', 64, 1447.42);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user043', 'HDFCBANK.NS', 15, 1584.03);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user043', 'MARUTI.NS', 69, 9724.11);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user043', 'BAJFINANCE.NS', 95, 7532.85);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user043', 'MRK', 61, 100.48);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user043', 'META', 86, 294.03);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user043', 'BAJAJFINSV.NS', 21, 1518.74);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user043', 'HINDUNILVR.NS', 59, 2394.87);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user044', 'SBIN.NS', 25, 595.75);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user044', 'UNH', 69, 470.12);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user044', 'RELIANCE.NS', 32, 2501.14);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user044', 'HDFCBANK.NS', 54, 1607.57);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user044', 'JPM', 75, 133.99);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user045', 'POWERGRID.NS', 95, 232.58);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user045', 'ASIANPAINT.NS', 10, 3214.11);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user045', 'BAJFINANCE.NS', 56, 6942.57);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user046', 'HINDUNILVR.NS', 15, 2470.11);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user046', 'WIPRO.NS', 81, 412.43);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user046', 'POWERGRID.NS', 91, 241.52);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user047', 'INFY.NS', 53, 1406.06);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user047', 'WIPRO.NS', 66, 416.68);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user047', 'AMZN', 84, 125.24);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user048', 'INTC', 25, 33.40);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user048', 'PG', 60, 142.77);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user048', 'VZ', 54, 34.25);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user048', 'BHARTIARTL.NS', 39, 873.66);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user048', 'DIS', 56, 88.49);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user049', 'GOOGL', 12, 2908.79);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user049', 'WMT', 26, 144.95);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user049', 'TSLA', 77, 214.95);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user049', 'INFY.NS', 92, 1367.03);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user049', 'ASIANPAINT.NS', 77, 3047.25);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user049', 'M&M.NS', 88, 1561.54);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user049', 'AXISBANK.NS', 68, 942.00);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user050', 'BAJFINANCE.NS', 91, 7382.10);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user050', 'NTPC.NS', 74, 202.99);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user050', 'BAC', 61, 28.87);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user050', 'LT.NS', 49, 2492.77);
INSERT INTO dummy_stock_portfolio (user_id, stock_symbol, quantity, purchase_price) VALUES ('user050', 'MRK', 59, 103.28);