input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [logger_name] =~ "OrderService" {
    mutate {
      add_tag => ["trading_transaction"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
